import type { Topic } from "../types";

export const grade11Topics: Topic[] = [
  {
    id: "gdila-udeicha",
    name: "גדילה ודעיכה מעריכית",
    strand: "אשכול חברה ומדע",
    description: "מודל y = y₀ · qᵗ וחישוב הכמות אחרי מספר שנים.",
    generatorId: "exponential-growth",
    studyLevel: 3,
  },
  {
    id: "mishvaa-maarichit",
    name: "משוואות מעריכיות",
    strand: "אשכול חברה ומדע",
    description: "פתרון משוואה מהצורה qˣ = c עם מעריך שלם.",
    generatorId: "exponential-equation",
    studyLevel: 3,
  },
  {
    id: "stiyat-teken",
    name: "סטיית תקן",
    strand: "אשכול חברה ומדע",
    description: "חישוב ממוצע וסטיית תקן של אוסף נתונים.",
    generatorId: "standard-deviation",
    studyLevel: 3,
  },
  {
    id: "histabrut-mitkademet",
    name: "הסתברות מתקדמת",
    strand: "אשכול חברה ומדע",
    description: "מאורעות תלויים ובלתי תלויים והסתברות מותנית.",
    generatorId: "conditional-probability",
    studyLevel: 3,
  },
  {
    id: "ribit-deribit",
    name: "ריבית דריבית",
    strand: "אשכול פיננסי-כלכלי",
    description: "חיסכון והלוואות לפי המודל המעריכי.",
    generatorId: "compound-interest",
    studyLevel: 3,
  },
  {
    id: "achuzim-tsarchaniim",
    name: "אחוזים בהקשר צרכני",
    strand: "אשכול פיננסי-כלכלי",
    description: "הנחות, מע\"מ ומציאת המחיר לפני ההנחה.",
    generatorId: "consumer-percent",
    studyLevel: 3,
  },
  {
    id: "yachas-uproportzia",
    name: "יחס ופרופורציה",
    strand: "אשכול התמצאות במישור ובמרחב",
    description: "חלוקה לפי יחס והשלמת ערך חסר בפרופורציה.",
    generatorId: "ratio",
    studyLevel: 3,
  },
  {
    id: "kne-mida",
    name: "קנה מידה",
    strand: "אשכול התמצאות במישור ובמרחב",
    description: "מעבר בין אורך במפה או בשרטוט לאורך במציאות.",
    generatorId: "scale",
    studyLevel: 3,
  },
  {
    id: "dimyon-meshulashim",
    name: "דמיון משולשים",
    strand: "אשכול התמצאות במישור ובמרחב",
    description: "יחס דמיון ויחסי צלעות, היקפים ושטחים.",
    generatorId: "similar-triangles",
    studyLevel: 3,
  },
  {
    id: "trigonometria",
    name: "טריגונומטריה במשולש ישר זווית",
    strand: "אשכול התמצאות במישור ובמרחב",
    description: "סינוס, קוסינוס וטנגנס ומציאת צלע לפי זווית.",
    generatorId: "right-triangle-trig",
    studyLevel: 3,
  },
  {
    id: "pitagoras",
    name: "משפט פיתגורס",
    strand: "אשכול התמצאות במישור ובמרחב",
    description: "מציאת יתר או ניצב במשולש ישר זווית.",
    generatorId: "pythagoras",
    studyLevel: 3,
  },
];

export default grade11Topics;
