import type { Topic } from "../types";

export const grade9Topics: Topic[] = [
  {
    id: "hukey-hezkot",
    name: "חוקי חזקות",
    strand: "תחום אלגברי",
    description: "כפל, חילוק וחזקה של חזקה.",
    generatorId: "power-laws",
    levels: [1, 2],
  },
  {
    id: "ktiv-madai",
    name: "כתיב מדעי",
    strand: "תחום אלגברי",
    description: "מעבר בין מספר רגיל לכתיב מדעי בעזרת חזקות של 10.",
    generatorId: "scientific-notation",
  },
  {
    id: "hukey-shorashim",
    name: "חוקי שורשים",
    strand: "תחום אלגברי",
    description: "פישוט שורש, כפל וחילוק שורשים והוצאת גורם מהשורש.",
    generatorId: "root-laws",
  },
  {
    id: "kefel-mekutzar",
    name: "נוסחאות הכפל המקוצר",
    strand: "תחום אלגברי",
    description: "פתיחת (a+b)², (a−b)² ו-(a−b)(a+b).",
    generatorId: "special-products",
  },
  {
    id: "perok-legormim",
    name: "פירוק לגורמים",
    strand: "תחום אלגברי",
    description: "הוצאת גורם משותף ופירוק לפי הפרש ריבועים.",
    generatorId: "factoring",
  },
  {
    id: "perok-trinom",
    name: "פירוק טרינום",
    strand: "תחום אלגברי",
    description: "פירוק ביטוי מהצורה x² + bx + c למכפלת שני גורמים.",
    generatorId: "factor-trinomial",
  },
  {
    id: "mishvaa-ribuit",
    name: "משוואות ריבועיות",
    strand: "תחום אלגברי",
    description: "פתרון משוואה ריבועית בעלת שני פתרונות שלמים.",
    generatorId: "quadratic-equation",
  },
  {
    id: "shvarim-algebriim",
    name: "שברים אלגבריים",
    strand: "תחום אלגברי",
    description: "צמצום שבר אלגברי בעזרת פירוק לגורמים.",
    generatorId: "algebraic-fractions",
  },
  {
    id: "funktsia-ribuit",
    name: "הפונקציה הריבועית",
    strand: "תחום אלגברי",
    description: "קודקוד, ציר סימטריה וחיתוך עם ציר ה-y של פרבולה.",
    generatorId: "parabola",
  },
  {
    id: "zaviot-bemrubaim",
    name: "זוויות במרובעים",
    strand: "תחום גאומטרי",
    description: "חישובי זוויות במקבילית, בטרפז, במרובע ובמשולש שווה שוקיים.",
    generatorId: "quadrilateral-angles",
  },
  {
    id: "mishvaot-shvarim",
    name: "משוואות עם שברים אלגבריים",
    strand: "תחום אלגברי",
    description: "פתרון משוואה שבה הנעלם מופיע במכנה.",
    generatorId: "rational-equation",
  },
  {
    id: "ee-shivyon-ribui",
    name: "אי-שוויון ריבועי",
    strand: "תחום אלגברי",
    description: "פתרון אי-שוויון ריבועי לפי שורשי הטרינום וכיוון הפרבולה.",
    generatorId: "quadratic-inequality",
  },
  {
    id: "maarechet-ribuit",
    name: "מערכת משוואות ממעלה שנייה",
    strand: "תחום אלגברי",
    description: "פתרון מערכת שבה משוואה אחת היא ממעלה שנייה.",
    generatorId: "quadratic-system",
  },
  {
    id: "hazazat-funktsia",
    name: "הזזות ומתיחות של פונקציה",
    strand: "תחום אלגברי",
    description: "כתיבת g(x) המתקבלת מ-f(x) בהזזה, בשיקוף ובמתיחה, כפולינום.",
    generatorId: "function-transform",
  },
];

export default grade9Topics;
